[identities]
altair-christian = "age15fjlypp3dt6jjgctv3dh2alywmpkdamn20srnsr0q9vr3nznesmqt9gp2u"
altair-root = "age1uzy4gk7pmmt2nskdqa43t5sjf4zyddj6wl22vjct9eh2hn59rgasnhflwf"
io-nix-on-droid = "age1vt2g4gya2pz73epwc0zcqcwr44t5u27mnptpswuxjpfvxgkrwqeq9rsg8d"
malmok-christian = "age1xevq6ttjadu7csmnxcdze95qvcq78kk5ce54ptutenj96rw4e9fsu6el7w"
malmok-root = "age19mcppvd32wxe0qdzkc9gh9hdz0sxz0k6yy8w6fnfaupas7dp0qdqr36wvk"
sirius-christian = "age1z8dp8he50ksaz0zqg6tasmfmmlgplsva9jeh4lmvu72wx82l6c5qhdmz7y"
sirius-root = "age1ysardqq0elh2l9gxf8aune4kcjkzr8m34pxja4ctfexv7wd65g3srdy4rx"


[groups]
all = [
  "altair-christian",
  "altair-root",
  "io-nix-on-droid",
  "malmok-christian",
  "malmok-root",
  "sirius-christian",
  "sirius-root",
]
root = [
  "altair-root",
  "malmok-root",
  "sirius-root",
]
christian = [
  "altair-christian",
  "malmok-christian",
  "sirius-christian",
]
nix-on-droid = [
  "io-nix-on-droid",
]

[[paths]]
glob = "secrets/nixos/*.age"
groups = [ "root" ]

[[paths]]
glob = "secrets/home/christian/*.age"
groups = [ "christian" ]

[[paths]]
glob = "secrets/nix-on-droid/*.age"
groups = [ "nix-on-droid" ]

[[paths]]
glob = "secrets/nixos/malmok/*.age"
identities = [ "malmok-root" ]
