[identities]
home-christian = "age15fjlypp3dt6jjgctv3dh2alywmpkdamn20srnsr0q9vr3nznesmqt9gp2u"
nixos-altair = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEqT+eVFO2Rb6Il8GndgygdOKOhVa0TLp/TTnkm0LDLQ"
nixos-hyperion = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJLSEMUTH+nZ9APeH5FbX0YtwmGFxhaXFfxRwrto0Kfk"
nixos-malmok = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPVGn5uLSxWyFAgW0Q8l8B5XXsn52b5utV06zthGZkuD"
nixos-sirius-b = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA2PKuhWG5IQgiSzor/foQg3LgmrCvYKO80y/5UUzMb4"
nix-on-droid-io = "age1vt2g4gya2pz73epwc0zcqcwr44t5u27mnptpswuxjpfvxgkrwqeq9rsg8d"

[groups]
all = [
  "home-christian",
  "nixos-altair",
  "nixos-hyperion",
  "nixos-malmok",
  "nixos-sirius-b",
  "nix-on-droid-io",
]
nixos = [
  "nixos-altair",
  "nixos-hyperion",
  "nixos-malmok",
  "nixos-sirius-b",
]
nix-on-droid = [
  "nix-on-droid-io",
]

[[paths]]
glob = "secrets/nixos/*.age"
groups = [ "nixos" ]

[[paths]]
glob = "secrets/home/christian/*.age"
identities = [ "home-christian" ]

[[paths]]
glob = "secrets/nixos/hyperion/*.age"
identities = [ "nixos-hyperion" ]

[[paths]]
glob = "secrets/nixos/malmok/*.age"
identities = [ "nixos-malmok" ]

[[paths]]
glob = "secrets/nix-on-droid/*.age"
groups = [ "nix-on-droid" ]
