name: Build and test
on: [ push ]

jobs:
  nix-ci:
    uses: christianharke/flake-commons/.github/workflows/nix-ci.yml@main
    with:
      branch: ${{ github.ref_name }}
      nix-command: flake check --impure
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
