---
name: "Update inputs"
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  nix-update:
    uses: "rake5k/flake-commons/.github/workflows/nix-update.yml@main"
    with:
      base-branch: "master"
      nix-check-command: "flake check --impure"
    secrets:
      CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      DEPLOY_KEY_SUBMODULES: "${{ secrets.NIXCFG_SECRETS_DEPLOY_KEY }}"
      KNOWN_HOSTS: "${{ secrets.KNOWN_HOSTS_CODE_HARKE_CH }}"
