name: Update inputs
on:
  schedule:
    - cron: 0 5 * * *

jobs:
  nix-update:
    uses: rake5k/flake-commons/.github/workflows/nix-update.yml@main
    with:
      base-branch: master
      nix-check-command: flake check --impure
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
