---
name: "Update inputs"
on:  # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:

jobs:
  nix-update:
    uses: "rake5k/flake-commons/.github/workflows/update-flake-lock.yml@main"
    secrets:
      GH_PRIVATE_INPUT_TOKEN: "${{ secrets.NIXCFG_SECRETS_TOKEN }}"
