name: Update inputs
on:
  schedule:
    - cron: 0 2 * * *

jobs:
  nix-update:
    uses: christianharke/flake-commons/.github/workflows/nix-update.yml@main
    with:
      base-branch: master
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
